package kotlinx.coroutines.internal;

/* loaded from: classes2.dex */
public final class ExceptionSuccessfullyProcessed extends Exception {

    /* renamed from: o, reason: collision with root package name */
    public static final ExceptionSuccessfullyProcessed f38764o = new ExceptionSuccessfullyProcessed();

    private ExceptionSuccessfullyProcessed() {
    }
}
